### ISSUE TITLE
Python 3.6 still specified in readme

### ISSUE THREAD

**Issue by asarnow** [tbepler/topaz#222]
~The required python version might need to be jumped to 3.8 (when `typing.Literal` became available), or `typing_extensions` added to the requirements and the imports changed to that module instead (which should still work in Python 3.8 and above). Otherwise there is an `ImportError: cannot import name 'Literal'` when running topaz.~

Current requirements / meta.yaml are good, it's just in the readme where it still says 3.6.

**Comment by asarnow** [comment]
Mistaken or fixed already.
